name: insighted
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Core
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.0.15 

  
  # API & File Handling
  http: ^1.2.1
  file_picker: ^8.0.5
  http_parser: ^4.0.2
  
  # Animations & Charts
  lottie: ^3.1.2
  fl_chart: ^0.68.0
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/